2021-01-18 16:43:36,396 - HMI.py[line:375] - INFO: i-shopOCR user interface has been closed.

2021-01-18 16:46:54,294 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 16:47:45,823 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 16:47:45,946 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 16:48:13,233 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 18:33:12,190 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 18:35:03,530 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:35:03,650 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:43:56,132 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:43:56,369 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:43:56,593 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:43:56,827 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:43:56,941 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:44:11,369 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:44:11,597 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:11,815 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:44:12,046 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:12,160 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:44:13,787 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:44:14,017 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:14,236 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:44:14,469 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:14,581 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:44:16,547 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:44:16,776 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:16,995 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:44:17,228 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:17,340 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:45:57,744 - HMI.py[line:379] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 18:46:31,135 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:46:31,270 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:46:32,994 - HMI.py[line:379] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 18:59:04,859 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:59:04,964 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:59:11,709 - HMI.py[line:379] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 19:06:11,392 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 19:08:31,793 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

