2021-01-18 16:43:36,396 - HMI.py[line:375] - INFO: i-shopOCR user interface has been closed.

2021-01-18 16:46:54,294 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 16:47:45,823 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 16:47:45,946 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 16:48:13,233 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 18:33:12,190 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 18:35:03,530 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:35:03,650 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:43:56,132 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:43:56,369 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:43:56,593 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:43:56,827 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:43:56,941 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:44:11,369 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:44:11,597 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:11,815 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:44:12,046 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:12,160 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:44:13,787 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:44:14,017 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:14,236 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:44:14,469 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:14,581 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:44:16,547 - HMI.py[line:379] - INFO: Refreshing the camera configurations, restarting...
2021-01-18 18:44:16,776 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:16,995 - HMI.py[line:379] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-18 18:44:17,228 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:44:17,340 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:45:57,744 - HMI.py[line:379] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 18:46:31,135 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:46:31,270 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:46:32,994 - HMI.py[line:379] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 18:59:04,859 - HMI.py[line:379] - INFO: Found camera NR0190090349, connecting...
2021-01-18 18:59:04,964 - HMI.py[line:379] - INFO: Successfully connected camera NR0190090349.
2021-01-18 18:59:11,709 - HMI.py[line:379] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 19:06:11,392 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 19:08:31,793 - HMI.py[line:379] - INFO: i-shopOCR user interface has been closed.

2021-01-18 19:13:34,495 - HMI.py[line:380] - INFO: Found camera NR0190090349, connecting...
2021-01-18 19:13:34,621 - HMI.py[line:380] - INFO: Successfully connected camera NR0190090349.
2021-01-18 19:13:43,633 - HMI.py[line:380] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-18 19:13:46,947 - HMI.py[line:380] - INFO: Found camera NR0190090349, connecting...
2021-01-18 19:13:47,059 - HMI.py[line:380] - INFO: Successfully connected camera NR0190090349.
2021-01-18 19:14:44,340 - HMI.py[line:380] - INFO: i-shopOCR user interface has been closed.

2021-01-19 11:17:06,656 - HMI.py[line:386] - WARNING: Camera with the serial number NR0190090349 does not in the list.
2021-01-19 11:19:25,576 - HMI.py[line:386] - INFO: i-shopOCR user interface has been closed.

2021-01-19 11:29:31,357 - HMI.py[line:386] - INFO: i-shopOCR user interface has been closed.

2021-01-19 16:57:12,983 - HMI.py[line:383] - INFO: Found camera NR0190090349, connecting...
2021-01-19 16:57:13,104 - HMI.py[line:383] - INFO: Successfully connected camera NR0190090349.
2021-01-19 16:57:21,797 - HMI.py[line:383] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-19 16:57:42,986 - HMI.py[line:383] - INFO: Found camera NR0190090349, connecting...
2021-01-19 16:57:43,099 - HMI.py[line:383] - INFO: Successfully connected camera NR0190090349.
2021-01-19 16:58:13,474 - HMI.py[line:383] - INFO: Refreshing the camera configurations, restarting...
2021-01-19 16:58:13,703 - HMI.py[line:383] - INFO: Found camera NR0190090349, connecting...
2021-01-19 16:58:13,925 - HMI.py[line:383] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-19 16:58:14,152 - HMI.py[line:383] - INFO: Found camera NR0190090349, connecting...
2021-01-19 16:58:14,263 - HMI.py[line:383] - INFO: Successfully connected camera NR0190090349.
2021-01-19 16:58:16,708 - HMI.py[line:383] - INFO: Refreshing the camera configurations, restarting...
2021-01-19 16:58:16,933 - HMI.py[line:383] - INFO: Found camera NR0190090349, connecting...
2021-01-19 16:58:17,154 - HMI.py[line:383] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-19 16:58:17,392 - HMI.py[line:383] - INFO: Found camera NR0190090349, connecting...
2021-01-19 16:58:17,504 - HMI.py[line:383] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:09:42,987 - HMI.py[line:383] - ERROR: Camera connection is interrupted, please reconnect.
2021-01-19 17:13:32,794 - HMI.py[line:386] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:13:32,919 - HMI.py[line:386] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:13:44,796 - HMI.py[line:386] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:13:44,912 - HMI.py[line:386] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:14:20,664 - HMI.py[line:386] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:14:20,772 - HMI.py[line:386] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:14:26,014 - HMI.py[line:386] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:14:26,125 - HMI.py[line:386] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:29:41,992 - HMI.py[line:386] - INFO: i-shopOCR user interface has been closed.

2021-01-19 17:29:59,039 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:29:59,162 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:30:13,709 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:13,821 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:30:18,567 - HMI.py[line:381] - INFO: Refreshing the camera configurations, restarting...
2021-01-19 17:30:18,805 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:19,026 - HMI.py[line:381] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-19 17:30:19,247 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:19,359 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:30:23,664 - HMI.py[line:381] - INFO: Refreshing the camera configurations, restarting...
2021-01-19 17:30:23,902 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:24,124 - HMI.py[line:381] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-19 17:30:24,355 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:24,467 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:30:32,435 - HMI.py[line:381] - INFO: Refreshing the camera configurations, restarting...
2021-01-19 17:30:32,672 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:32,895 - HMI.py[line:381] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-19 17:30:33,126 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:30:33,242 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:31:09,331 - HMI.py[line:381] - INFO: Refreshing the camera configurations, restarting...
2021-01-19 17:31:09,557 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:31:09,781 - HMI.py[line:381] - WARNING: DeviceManager.open_device_by_sn:{-8}{The device has already been opened}
2021-01-19 17:31:10,006 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:31:10,117 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:37:15,007 - HMI.py[line:381] - INFO: i-shopOCR user interface has been closed.

2021-01-19 17:37:40,332 - HMI.py[line:382] - INFO: Found camera NR0190090349, connecting...
2021-01-19 17:37:40,444 - HMI.py[line:382] - INFO: Successfully connected camera NR0190090349.
2021-01-19 17:38:01,621 - HMI.py[line:382] - INFO: i-shopOCR user interface has been closed.

2021-01-19 18:08:30,031 - HMI.py[line:382] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:08:30,151 - HMI.py[line:382] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:09:02,422 - HMI.py[line:382] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:09:02,535 - HMI.py[line:382] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:09:30,712 - HMI.py[line:382] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:09:30,831 - HMI.py[line:382] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:11:50,760 - HMI.py[line:382] - INFO: i-shopOCR user interface has been closed.

2021-01-19 18:17:49,723 - HMI.py[line:381] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:17:49,839 - HMI.py[line:381] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:20:52,051 - HMI.py[line:384] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:20:52,160 - HMI.py[line:384] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:21:27,299 - HMI.py[line:384] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:21:27,412 - HMI.py[line:384] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:21:30,428 - HMI.py[line:384] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:29,831 - HMI.py[line:385] - INFO: Found camera NR0190090349, connecting...
2021-01-19 18:22:29,949 - HMI.py[line:385] - INFO: Successfully connected camera NR0190090349.
2021-01-19 18:22:33,657 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:33,685 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:33,689 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:35,471 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:37,231 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:37,795 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:38,077 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:38,232 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:38,394 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:38,525 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:22:38,693 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:23:37,007 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:23:39,737 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:23:53,189 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-19 18:23:58,371 - HMI.py[line:385] - INFO: i-shopOCR user interface has been closed.

2021-01-20 14:44:29,720 - HMI.py[line:384] - INFO: 发现相机NR0190090349， 连接相机 ...
2021-01-20 14:44:29,843 - HMI.py[line:384] - INFO: Successfully connected camera NR0190090349.
2021-01-20 14:50:06,671 - HMI.py[line:385] - INFO: 发现相机NR0190090349， 连接相机 ...
2021-01-20 14:50:06,784 - HMI.py[line:385] - INFO: Successfully connected camera NR0190090349.
2021-01-20 14:50:09,718 - HMI.py[line:385] - INFO: i-shopOCR user interface has been closed.

2021-01-20 14:53:43,548 - HMI.py[line:385] - INFO: 发现相机NR0190090349， 连接相机 ...
2021-01-20 14:53:43,671 - HMI.py[line:385] - INFO: Successfully connected camera NR0190090349.
2021-01-20 14:54:57,599 - HMI.py[line:385] - INFO: 发现相机NR0190090349， 连接相机 ...
2021-01-20 14:54:57,713 - HMI.py[line:385] - INFO: Successfully connected camera NR0190090349.
2021-01-20 15:45:04,415 - HMI.py[line:385] - INFO: 发现相机NR0190090349， 连接相机 ...
2021-01-20 15:45:04,540 - HMI.py[line:385] - INFO: Successfully connected camera NR0190090349.
2021-01-20 15:45:19,492 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-20 15:45:21,524 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-20 15:45:23,740 - HMI.py[line:385] - WARNING: Error using the patch method for recognition.
2021-01-20 15:47:24,111 - HMI.py[line:385] - INFO: i-shopOCR user interface has been closed.

